import { Product } from "./types";

export const PRODUCTS: Product[] = [
  // 초기 (적응기)
  {
    id: "meal-early-1",
    category: "diet_meal",
    name: "저칼로리 균형식 도시락 세트 (5끼)",
    description: "탄단지 균형을 맞춘 350kcal대 도시락. 다이어트 적응기에 적합.",
    price: 39000,
    imageEmoji: "🥗",
    suitablePhase: "early",
    servingInfo: "1끼 구성 (총 5끼 배송)",
    kcal: 358,
    composition: [
      { name: "닭가슴살", brand: "하림", amount: "100g" },
      { name: "발아현미밥", amount: "100g" },
      { name: "브로콜리·당근 무침", amount: "80g" },
      { name: "삶은 달걀", amount: "1개(50g)" },
      { name: "저염 강된장", amount: "20g" },
    ],
  },
  {
    id: "meal-early-2",
    category: "diet_meal",
    name: "대체식 쉐이크 (14포)",
    description: "한 끼 대체용 고식이섬유 쉐이크. 포만감과 영양을 동시에.",
    price: 32000,
    imageEmoji: "🥤",
    suitablePhase: "early",
    servingInfo: "1포(25g) 기준, 물 200ml에 희석",
    kcal: 152,
    composition: [
      { name: "분리대두단백", brand: "그린데이", amount: "12g" },
      { name: "이눌린 식이섬유", amount: "5g" },
      { name: "비타민·무기질 프리믹스", amount: "3g" },
      { name: "저칼로리 감미료(스테비아)", amount: "0.5g" },
    ],
  },
  {
    id: "supp-early-1",
    category: "supplement",
    manufacturer: "그린팜제약",
    name: "기초대사 활성 비타민 B군",
    description: "적응기 기초대사량 유지를 돕는 종합 비타민 B 복합제.",
    price: 21000,
    imageEmoji: "💊",
    suitablePhase: "early",
    servingInfo: "1일 1정 기준 (60정, 60일분)",
    composition: [
      { name: "비타민 B1(티아민)", amount: "25mg" },
      { name: "비타민 B2(리보플라빈)", amount: "25mg" },
      { name: "비타민 B6(피리독신)", amount: "20mg" },
      { name: "비타민 B12(코발라민)", amount: "100㎍" },
      { name: "나이아신아마이드", amount: "30mg" },
    ],
  },

  // 중기 (본격기)
  {
    id: "meal-mid-1",
    category: "diet_meal",
    name: "고단백 저탄수 도시락 세트 (5끼)",
    description: "근손실 방지를 위한 고단백 저탄수 구성. 본격 감량기 추천.",
    price: 45000,
    imageEmoji: "🍱",
    suitablePhase: "mid",
    servingInfo: "1끼 구성 (총 5끼 배송)",
    kcal: 412,
    composition: [
      { name: "닭가슴살", brand: "하림", amount: "150g" },
      { name: "현미퀴노아밥", amount: "80g" },
      { name: "구운 파프리카·애호박", amount: "100g" },
      { name: "아몬드", amount: "10g" },
    ],
  },
  {
    id: "meal-mid-2",
    category: "diet_meal",
    name: "저당 단백 그래놀라",
    description: "아침 대용, 저당 고단백 그래놀라 500g.",
    price: 18000,
    imageEmoji: "🥣",
    suitablePhase: "mid",
    servingInfo: "1회 제공량 60g 기준 (총 500g, 약 8회분)",
    kcal: 246,
    composition: [
      { name: "압착 귀리(오트밀)", amount: "40g" },
      { name: "유청단백파우더", brand: "매일유업 셀렉스", amount: "10g" },
      { name: "저당 크랜베리", amount: "5g" },
      { name: "아몬드 슬라이스", amount: "5g" },
    ],
  },
  {
    id: "supp-mid-1",
    category: "supplement",
    manufacturer: "바이오넥스",
    name: "WPI 분리유청 단백질 보충제",
    description: "근육량 유지를 위한 고순도 유청 단백질 (초코맛, 900g).",
    price: 42000,
    imageEmoji: "🧃",
    suitablePhase: "mid",
    servingInfo: "1회 제공량 30g(2스쿱) 기준, 900g/30회분",
    kcal: 118,
    composition: [
      { name: "분리유청단백(WPI)", amount: "25g (단백질 함량 92%)" },
      { name: "코코아파우더", amount: "2g" },
      { name: "천연 감미료(수크랄로스)", amount: "0.1g" },
    ],
  },
  {
    id: "supp-mid-2",
    category: "supplement",
    manufacturer: "그린팜제약",
    name: "지방분해 촉진 보조제 (가르시니아 복합)",
    description: "가르시니아캄보지아 추출물 함유. 4주 집중 관리용.",
    price: 29000,
    imageEmoji: "🌿",
    suitablePhase: "mid",
    servingInfo: "1일 2캡슐 기준 (60캡슐, 30일분)",
    composition: [
      { name: "가르시니아캄보지아 추출물(HCA 60%)", amount: "500mg" },
      { name: "L-카르니틴 타르트레이트", amount: "100mg" },
      { name: "녹차추출물(카테킨 40%)", amount: "50mg" },
    ],
  },

  // 후기 (유지기)
  {
    id: "meal-late-1",
    category: "diet_meal",
    name: "체중 유지 밸런스 도시락 (5끼)",
    description: "리바운드 방지를 위한 영양 밸런스 유지식.",
    price: 41000,
    imageEmoji: "🍲",
    suitablePhase: "late",
    servingInfo: "1끼 구성 (총 5끼 배송)",
    kcal: 389,
    composition: [
      { name: "연어살", brand: "노르웨이산", amount: "120g" },
      { name: "현미밥", amount: "100g" },
      { name: "제철 나물 반찬", amount: "100g" },
      { name: "미소된장국", amount: "150ml" },
    ],
  },
  {
    id: "supp-late-1",
    category: "supplement",
    manufacturer: "바이오넥스",
    name: "유지기 종합 영양제",
    description: "감량 후 체중 유지를 돕는 종합 미네랄·비타민 제품.",
    price: 25000,
    imageEmoji: "🍀",
    suitablePhase: "late",
    servingInfo: "1일 1정 + 1캡슐 기준 (60일분)",
    composition: [
      { name: "종합비타민·미네랄 정", amount: "1정 (13종)" },
      { name: "오메가-3(EPA·DHA)", amount: "500mg" },
      { name: "마그네슘", amount: "100mg" },
    ],
  },
];

export function productById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
